# Generated by Django 3.2 on 2023-05-06 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TblAlumno',
            fields=[
                ('alumno_id', models.AutoField(primary_key=True, serialize=False)),
                ('alumno_nombre', models.CharField(max_length=100)),
                ('alumno_email', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_alumno',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TblProfesor',
            fields=[
                ('profesor_id', models.AutoField(primary_key=True, serialize=False)),
                ('profesor_nombre', models.CharField(max_length=255)),
                ('profesor_email', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tbl_profesor',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TblMatricula',
            fields=[
                ('matricula_id', models.AutoField(primary_key=True, serialize=False)),
                ('matricula_grupo', models.CharField(max_length=255)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='web.tblalumno')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='web.tblprofesor')),
            ],
            options={
                'db_table': 'tbl_matricula',
                'managed': True,
            },
        ),
    ]
